#Max number of times you can use /back
#Range: > 0
maxBack = 10
#Max homes
#Range: > 0
maxHomes = 3
#/back cooldown in seconds
#Range: 0 ~ 604800
backCooldown = 60
#/spawn cooldown in seconds
#Range: 0 ~ 604800
spawnCooldown = 60
#/warp cooldown in seconds
#Range: 0 ~ 604800
warpCooldown = 60
#/home cooldown in seconds
#Range: 0 ~ 604800
homeCooldown = 60
#/tpa cooldown in seconds
#Range: 0 ~ 604800
tpaCooldown = 60
#/rtp cooldown in seconds
#Range: 0 ~ 604800
rtpCooldown = 600
#Number of tries before /rtp gives up
#Range: 1 ~ 1000
rtpMaxTries = 100
#/rtp min distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMinDistance = 500.0
#/rtp max distance from spawn point
#Range: 0.0 ~ 3.0E7
rtpMaxDistance = 5000.0

