
[items]
	#If this is set to true, elytras will use lower quality textures for the banners (requires reload)
	elytras_use_low_quality_banners = false
	#If this is set to true, customizing an elytra with a banner will use your cape texture (if present) as the base pattern, instead of a plain base
	elytras_base_pattern_is_cape_texture = true

