
#Lang Settings
[lang]
	#Server language codes are based off the Minecraft .lang files. See https://minecraft.gamepedia.com/Language for list.
	serverLang = "en_us"

#Util Settings
[util]
	#Disable ServerStop Update Checker Message
	disableUpdateCheck = false
	#Shutdown the Server Even if Players are Online
	stopWhenPlayersOnline = true

#Monday Settings
[monday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableMonday = true
	#On Monday this is the hour the server will auto-shutdown. It uses 24-hour time.
	mondayHour = []
	#On Monday this is the minute the server will auto-shutdown.
	mondayMinute = []

#Tuesday Settings
[tuesday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableTuesday = true
	#On Tuesday this is the hour the server will auto-shutdown. It uses 24-hour time.
	tuesdayHour = []
	#On Tuesday this is the minute the server will auto-shutdown.
	tuesdayMinute = []

#Wednesday Settings
[wednesday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableWednesday = true
	#On Wednesday this is the hour the server will auto-shutdown. It uses 24-hour time.
	wednesdayHour = []
	#On Wednesday this is the minute the server will auto-shutdown.
	wednesdayMinute = []

#Thursday Settings
[thursday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableThursday = true
	#On Thursday this is the hour the server will auto-shutdown. It uses 24-hour time.
	thursdayHour = []
	#On Thursday this is the minute the server will auto-shutdown.
	thursdayMinute = []

#Friday Settings
[friday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableFriday = true
	#On Friday this is the hour the server will auto-shutdown. It uses 24-hour time.
	fridayHour = []
	#On Friday this is the minute the server will auto-shutdown.
	fridayMinute = []

#Saturday Settings
[saturday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableSaturday = true
	#On Saturday this is the hour the server will auto-shutdown. It uses 24-hour time.
	saturdayHour = []
	#On Saturday this is the minute the server will auto-shutdown.
	saturdayMinute = []

#Sunday Settings
[sunday]
	#If this is enabled, at a time specified below the server will auto-shutdown.
	enableSunday = true
	#On Sunday this is the hour the server will auto-shutdown. It uses 24-hour time.
	sundayHour = []
	#On Sunday this is the minute the server will auto-shutdown.
	sundayMinute = []

